const products = [
    {
        id: 1,
        img300: "https://i.ibb.co/b696zjs/tomahawk-300.jpg",
        img500: "https://i.ibb.co/j50kJCs/tomahawk-500.jpg",
        title: "Tomahawk",
        description: "El tomahawk es un corte tradicional americano. Es ideal para hacer a la parrilla.",
        price: 1990,
        category: "ternera",
        stock: 12,
    },
    {
        id: 2,
        img300: "https://i.ibb.co/6NpryLK/costillas-de-cerdo-300.jpg",
        img500: "https://i.ibb.co/KVrSPn3/costillas-de-cerdo-500.jpg",
        title: "Costillas de cerdo",
        description: "La costillita de cerdo es ideal para hacerlo a la plancha.",
        price: 990,
        category: "cerdo",
        stock: 6,
    },
    {
        id: 3,
        img300: "https://i.ibb.co/MGHLhRz/chinchulin-300.jpg",
        img500: "https://i.ibb.co/nfKxnfv/chinchulin-500.jpg",
        title: "Chinchulin",
        description: "Un clásico de la parrilla, el chinchulin con su textura y sabor particular es infaltable para una parrillada Argentina.",
        price: 550,
        category: "achura",
        stock: 7,
    },
    {
        id: 4,
        img300: "https://i.ibb.co/Fm66jG1/morcilla-rosca-300.jpg",
        img500: "https://i.ibb.co/B2CdRLh/morcilla-rosca-500.jpg",
        title: "Morcilla Rosca",
        description: "La morcilla es un producto infaltable para el comienzo del disfrute de una parrillada, se puede consumir fría acompañando una picada o caliente como entrada del plato principal.",
        price: 950,
        category: "achura",
        stock: 8,
    },
    {
        id: 5,
        img300: "https://i.ibb.co/dmwFmX4/colita-de-cuadril-300.jpg",
        img500: "https://i.ibb.co/YZXV8Fg/colita-de-cuadril-500.jpg",
        title: "Colita de Cuadril",
        description: "Ideal para hacer al horno o a la parrilla, la colita de cuadril puede hacerse mechada o simplemente enteras",
        price: 1900,
        category: "ternera",
        stock: 9,
    },
    {
        id: 6,
        img300: "https://i.ibb.co/H7yDgQV/suprema-300.jpg",
        img500: "https://i.ibb.co/P6DXyLS/suprema-500.jpg",
        title: "Suprema de pollo",
        description: "La suprema es ideal para hacer a la plancha, versatil para poder agregarle una ssalsa gourmet o para rebozarlas.",
        price: 1900,
        category: "ave",
        stock: 10,
    }
     
]

export default products;